version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .development.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: