version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432 
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  localstack:
    container_name: 'aws-app-localstack'
    image: localstack/localstack
    ports:
      - '127.0.0.1:4566:4566'             
      - '127.0.0.1:3510-3559:4510-4559'   
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-} 
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3 
    volumes:
      - 'volume-localstack:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
    - aws_app_localstack_network    

networks:
    aws_app_localstack_network:
        driver: bridge

volumes:
  pgdata:
  volume-localstack:
    driver: local