name: CI/CD game_shop_be

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Actions checkout
        uses: actions/checkout@v3

      - name: Setting up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run lint
        run: npm run lint 

      - name: Run unit test:cov
        run: npm run test:cov
        env:
          CI: true

      - name: Archive coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage/lcov-report

  check-coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v2
        with:
          name: coverage
          path: coverage

      - name: Check coverage
        run: |
          COVERAGE_THRESHOLD=80
          COVERAGE=$(cat coverage/lcov-report/index.html | grep -oP 'Statements.+?(\d+)%' | grep -oP '\d+')
          
          COVERAGE=$(echo "$COVERAGE" | tr -d '\n')

          echo "Coverage is: $COVERAGE%"
          echo "Threshold is: $COVERAGE_THRESHOLD"

          if ! [[ "$COVERAGE" =~ ^[0-9]+$ ]] || [ "$COVERAGE" -lt "$COVERAGE_THRESHOLD" ]; then
            echo "Error: Test coverage is below the threshold ($COVERAGE%)."
            exit 1
          fi
